In [5]:
list1=[1,2,'3','tiger']
print(list1[1])
list2=[2,4,7,'jaguar',list1]
print(list2)

2
[2, 4, 7, 'jaguar', [1, 2, '3', 'tiger']]


In [2]:
import numpy as np

numarr = np.array([1,2,3,4,5,6,7,8])
print(numarr)
np2=np.arange(0,14,4)
print(np2)

[1 2 3 4 5 6 7 8]
[ 0  4  8 12]


In [18]:
numarr1=np.full((3,10),1)
print(numarr1,numarr1.shape)


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]] (3, 10)


In [15]:
np1=np.array(list1)
print(np1)

['1' '2' '3' 'tiger']


In [16]:
print(np1.shape)


(4,)


In [41]:
nos1=np.array([1,2,3,4,5,6,7,8,9,10])
print(nos1[::2]) 

[1 3 5 7 9]


In [12]:
np2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sqrt(np2d))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


In [13]:
np12=np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8])
print(np.absolute(np12))
print(np.log(np12))
print(np.min(np12))

[3 2 1 0 1 2 3 4 5 6 7 8]
[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154]
-3


C:\Users\rishi\AppData\Local\Temp\ipykernel_20032\1486180653.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(np12))
C:\Users\rishi\AppData\Local\Temp\ipykernel_20032\1486180653.py:3: RuntimeWarning: invalid value encountered in log
  print(np.log(np12))


In [14]:
np13=np12.view()
np14=np12.copy()
print(np12)
print(np13)
print(np14)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]


In [15]:
np13=np12.view()

np13[2]=-11
print(np12)
print(np13)
print(np14)

[ -3  -2 -11   0   1   2   3   4   5   6   7   8]
[ -3  -2 -11   0   1   2   3   4   5   6   7   8]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]


In [16]:
npq=np12.reshape(2,6)
print(npq)


[[ -3  -2 -11   0   1   2]
 [  3   4   5   6   7   8]]


In [17]:
npq=npq.reshape(-1)
print(npq)

[ -3  -2 -11   0   1   2   3   4   5   6   7   8]


In [18]:
for i in npq:
    print(i)
    


-3
-2
-11
0
1
2
3
4
5
6
7
8


In [19]:
npq=npq.reshape(3,4)
for i in npq:
    for j in i:
        print(j)

-3
-2
-11
0
1
2
3
4
5
6
7
8


In [25]:
 npq=np.array([-3 ,-2,-11,0,1,2,3 ,4,5,6, 7 ,  8])

In [26]:
for i in np.nditer(npq):
    print(i)

-3
-2
-11
0
1
2
3
4
5
6
7
8


In [28]:
x= np.where(npq == 3)
print(x)
print(x[0])
print(np.where(npq%2!=0))

(array([6], dtype=int64),)
[6]
(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)


In [30]:
filtered=[]
for thing in npq :
    if thing%2==0 :
        filtered.append(True)
    else :
        filtered.append(False)
print(npq)
print(filtered)
print(npq[filtered])    

[ -3  -2 -11   0   1   2   3   4   5   6   7   8]
[False, True, False, True, False, True, False, True, False, True, False, True]
[-2  0  2  4  6  8]


In [31]:
filtered=npq%2==0

print(npq)
print(filtered)
print(npq[filtered]) 

[ -3  -2 -11   0   1   2   3   4   5   6   7   8]
[False  True False  True False  True False  True False  True False  True]
[-2  0  2  4  6  8]
